  title: "mnot's Internet Drafts"
  description: My drafts currently under development
  remote_theme: mnot/theme@main
  titles_from_headings:
    enabled:     true
    strip_title: true
    collections: false